name: JSON Syntax Check

on:
  push:
    paths:
      - '**/*.json'
      - 'tests/**'
      - '.github/workflows/**'
      - 'README.md'
  pull_request:
    paths:
      - '**/*.json'
      - 'tests/**'
      - '.github/workflows/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests
        run: pytest -q
