name: JSON Syntax Check

on:
  push:
    paths:
      - '**/*.json'
      - 'tests/**'
      - '.github/workflows/**'
      - 'README.md'
  pull_request:
    paths:
      - '**/*.json'
      - 'tests/**'
      - '.github/workflows/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run JSON tests
        run: bun run test:json
